### ISSUE TITLE
Generate html form with CodeIgniter

### ISSUE THREAD

**Issue by alexteh** [gwinn/CodeIgniterBundle#1]
i stumble upon this article and i try to implement to codeigniter framework: 
https://coderwall.com/p/hldueq/generate-html-form-with-codeigniter

which link me to this github page:
"Yes, CodeIgniter can use layouts: github link"
Just want to ask whether it supports codeigniter 3.1.4?

**Comment by gwinn** [comment]
Don't think so, this code was created for 2.x version. But you can modify it for current version, if you want.

**Comment by alexteh** [comment]
okay thx, will do so if there is a point...
BTW whats the difference with ur layout library with 
$this->load->view and $this->parser->parse?
it seems pretty redundant to me dont you think? or is there any special feature that CI doesnt have?
